teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 5
    scale_linear:
      x: 0.2
    scale_linear_turbo:
      x: 0.4

    axis_linear:
      y: 2
    scale_linear:
      y: 0.2
    scale_linear_turbo:
      y: 0.4

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 0.6
    scale_angular_turbo:
      yaw: 0.7

    enable_button: 5  # L1 shoulder button
    enable_turbo_button: 4  # R1 shoulder button
